In [10]:
import pandas as pd
import numpy as np
data = [10, 12, 12, 13, 13, 14, 12, 14, 13, 19, 90]
df=pd.DataFrame(data,columns=['value'])
df['z-score']=(df['value']-df['value'].mean())/df['value'].std()
df['z-score']
outlier_z=df[df['z-score'].abs()>3]
print(outlier_z)

    value   z-score
10     90  3.001264

In [12]:
Q1=df['value'].quantile(0.25)
Q3=df['value'].quantile(0.75)
IQR=Q3-Q1
IQR
df_iqr=df[(df['value'] < Q1-1.5*IQR) | (df['value']> Q3+1.5*IQR)]
df_iqr

    value   z-score
9      19 -0.050803
10     90  3.001264

In [18]:
from sklearn.preprocessing import PowerTransformer
df['log']=np.log(df['value'])
df['sqrt']=np.sqrt(df['value'])
pt_yeojohnson=PowerTransformer(method='yeo-johnson')
df['yeojohnson']=pt_yeojohnson.fit_transform(df[['value']])
df

    value   z-score       log      sqrt  yeojohnson
0      10 -0.437684  2.302585  3.162278   -1.878199
1      12 -0.351711  2.484907  3.464102   -0.557099
2      12 -0.351711  2.484907  3.464102   -0.557099
3      13 -0.308724  2.564949  3.605551   -0.115632
4      13 -0.308724  2.564949  3.605551   -0.115632
5      14 -0.265737  2.639057  3.741657    0.232733
6      12 -0.351711  2.484907  3.464102   -0.557099
7      14 -0.265737  2.639057  3.741657    0.232733
8      13 -0.308724  2.564949  3.605551   -0.115632
9      19 -0.050803  2.944439  4.358899    1.211874
10     90  3.001264  4.499810  9.486833    2.219056